/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import dao.DaoDatos;
import dao.DaoHistorial;
import dao.DaoProducto;
import dao.impl.DaoImplDatos;
import dao.impl.DaoImplHistorial;
import dao.impl.DaoImplProducto;
import javax.swing.JTable;
import entidades.Datos;
import entidades.Historial;
import entidades.Producto;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import util.Memoria;

/**
 *
 * @author acer
 */
public class Editar extends javax.swing.JFrame {

    private DaoDatos dao;
    private DaoProducto daoP;
    private Producto daoV;

    private List<Datos> lista;
    public JTable table;
    public DefaultTableModel model;
    private Datos data;
    boolean dato = false;
    boolean valido;

    DateTimeFormatter formatter;
    private DaoHistorial daoH;
    private Historial dataH;
    DateTimeFormatter formato;
    DateTimeFormatter formato2;
    private String antesH;
    private String ahoraH;
    

    public Editar() {
        initComponents();
        dao = new DaoImplDatos();
        data = new Datos();

        daoP = new DaoImplProducto();
        daoV = new Producto();

        formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

        model = (DefaultTableModel) tblEditar.getModel();
        formato2 = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

        daoH = new DaoImplHistorial();
        dataH = new Historial();
        datosSelect();
        lblAdminAutorizacion.setText("Autorizado por : " + Memoria.get("autorizacion"));
        SeleccionBtn(valido);
        lblValidar.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEditar = new javax.swing.JTable();
        btnSeleccionar = new javax.swing.JButton();
        jlblID = new javax.swing.JLabel();
        lblAdminAutorizacion = new javax.swing.JLabel();
        lblValidar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        boxAlm4 = new javax.swing.JCheckBox();
        boxAlm3 = new javax.swing.JCheckBox();
        boxAlm2 = new javax.swing.JCheckBox();
        boxAlm1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        txtDteFechaIngreso = new com.toedter.calendar.JDateChooser();
        btnValidar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 51));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btnEditar.setBackground(new java.awt.Color(0, 0, 0));
        btnEditar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Editar Producto");

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha de ingreso:");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID:");

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cantidad:");

        tblEditar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Cantidad", "Fecha de ingreso", "Fehca de caducidad", "Ubicación"
            }
        ));
        jScrollPane2.setViewportView(tblEditar);

        btnSeleccionar.setBackground(new java.awt.Color(0, 0, 0));
        btnSeleccionar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        jlblID.setBackground(new java.awt.Color(255, 0, 102));
        jlblID.setForeground(new java.awt.Color(255, 255, 255));
        jlblID.setText("-");

        lblAdminAutorizacion.setForeground(new java.awt.Color(255, 0, 0));
        lblAdminAutorizacion.setText("jLabel2");

        lblValidar.setForeground(new java.awt.Color(255, 51, 51));
        lblValidar.setText("jLabel2");

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Almacén:");

        buttonGroup1.add(boxAlm4);
        boxAlm4.setForeground(new java.awt.Color(255, 255, 255));
        boxAlm4.setText("4");
        boxAlm4.setContentAreaFilled(false);
        boxAlm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxAlm4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(boxAlm3);
        boxAlm3.setForeground(new java.awt.Color(255, 255, 255));
        boxAlm3.setText("3");
        boxAlm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxAlm3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(boxAlm2);
        boxAlm2.setForeground(new java.awt.Color(255, 255, 255));
        boxAlm2.setText("2");
        boxAlm2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxAlm2MouseClicked(evt);
            }
        });
        boxAlm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxAlm2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(boxAlm1);
        boxAlm1.setForeground(new java.awt.Color(255, 255, 255));
        boxAlm1.setText("1");
        boxAlm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxAlm1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Producto:");

        txtDteFechaIngreso.setDateFormatString("yyyy-MM-dd");

        btnValidar.setBackground(new java.awt.Color(0, 0, 0));
        btnValidar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnValidar.setForeground(new java.awt.Color(255, 255, 255));
        btnValidar.setText("Validar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAdminAutorizacion)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtProducto)
                                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnValidar)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblValidar)
                                            .addGap(25, 25, 25))))
                                .addComponent(txtDteFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(97, 97, 97)
                                    .addComponent(boxAlm1)
                                    .addGap(28, 28, 28)
                                    .addComponent(boxAlm2)
                                    .addGap(30, 30, 30)
                                    .addComponent(boxAlm3)
                                    .addGap(28, 28, 28)
                                    .addComponent(boxAlm4))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton1)
                            .addGap(8, 8, 8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jlblID))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(btnSeleccionar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblAdminAutorizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblID, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(btnValidar))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValidar))))
                    .addComponent(jLabel7))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtDteFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(boxAlm4)
                        .addComponent(boxAlm3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(boxAlm2)
                        .addComponent(boxAlm1)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(12, 12, 12))
        );

        jlblID.getAccessibleContext().setAccessibleName("");
        jlblID.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (dato) {
            LocalDateTime fechaIngreso = txtDteFechaIngreso.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
            System.out.println(fechaIngreso);
            int seleccionFila = Integer.parseInt(tblEditar.getValueAt(tblEditar.getSelectedRow(), 0).toString());

            LocalDateTime fechaEntrega = fechaIngreso.plusDays(7);
            LocalDate localFechaEntrega = fechaEntrega.toLocalDate();

            String strFechaEntrega = fechaIngreso.format(formatter);
            String strFechaCaducidad = localFechaEntrega.plusDays(7).format(formatter);

            String almacen = "";
            if (boxAlm1.isSelected()) {
                almacen = "ALMACEN 1";
            } else if (boxAlm2.isSelected()) {
                almacen = "ALMACEN 2";
            } else if (boxAlm3.isSelected()) {
                almacen = "ALMACEN 3";
            } else if (boxAlm4.isSelected()) {
                almacen = "ALMACEN 4";
            }

            data.setCodProducto(txtProducto.getText());
            data.setCantidad(Integer.parseInt(txtCantidad.getText()));

            data.setFechaIngreso(strFechaEntrega);
            data.setFechaCaducidad(strFechaCaducidad);

            data.setUbicacion(almacen);
            data.setIdStock(seleccionFila);

            dao.datosEditar(data);
            dato = false;
            model.setRowCount(0);
            datosSelect();
            ahoraH ="ID: " +jlblID.getText()+ "\n " +
                    "Producto: " +txtProducto.getText()+ "\n " +
                    "Cantidad: " +txtCantidad.getText()+ "\n " +
                    "Almacen: " +almacen+"\n " +
                    "Entrega: " +strFechaEntrega ;
            dataH.setIdStock(seleccionFila);
            dataH.setIdUsuario((String) Memoria.get("codigoEmpleado"));
            dataH.setHistorial("EDITADO:\n Permiso:"+ Memoria.get("autorizacion")+" ("+ Memoria.get("codAdmin") +")\n Antes: \n "+ antesH + " \n Ahora: \n" + ahoraH);
            dataH.setFechaCambio(LocalDateTime.now().format(formato2));
            daoH.userInsertar(dataH);

            SeleccionBtn(valido);

        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila", "Información", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        try {
            jlblID.setText(model.getValueAt(tblEditar.getSelectedRow(), 0).toString());
            txtProducto.setText(model.getValueAt(tblEditar.getSelectedRow(), 1).toString());
            txtCantidad.setText(model.getValueAt(tblEditar.getSelectedRow(), 2).toString());
            String fecha = model.getValueAt(tblEditar.getSelectedRow(), 3).toString();
            String tipoAlmacen = (String) tblEditar.getValueAt(tblEditar.getSelectedRow(), 5);
            if ("ALMACEN 1".equals(tipoAlmacen)) {
                boxAlm1.setSelected(true);
            } else if ("ALMACEN 2".equals(tipoAlmacen)) {
                boxAlm2.setSelected(true);
            } else if ("ALMACEN 3".equals(tipoAlmacen)) {
                boxAlm3.setSelected(true);
            } else if ("ALMACEN 4".equals(tipoAlmacen)) {
                boxAlm4.setSelected(true);
            }

            LocalDate fechaCambio = LocalDate.parse(fecha, formatter);

            int dia = fechaCambio.getDayOfMonth();
            int mes = fechaCambio.getMonthValue();
            int año = fechaCambio.getYear();

            Calendar calendar = Calendar.getInstance();
            calendar.set(año, mes - 1, dia);

            txtDteFechaIngreso.setCalendar(calendar);
            antesH ="ID: "+ jlblID.getText()+ "\n " +
                    "Producto: "+ txtProducto.getText()+ "\n " +
                    "Cantidad: "+ txtCantidad.getText()+ "\n " +
                    "Almacen: " +tipoAlmacen+"\n " +
                    "Entrega: "+ fecha;
            btnValidar.setEnabled(true);
            dato = true;
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila", "Información", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        vistaMenu();
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void boxAlm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxAlm4ActionPerformed

    }//GEN-LAST:event_boxAlm4ActionPerformed

    private void boxAlm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxAlm3ActionPerformed

    }//GEN-LAST:event_boxAlm3ActionPerformed

    private void boxAlm2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxAlm2MouseClicked

    }//GEN-LAST:event_boxAlm2MouseClicked

    private void boxAlm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxAlm2ActionPerformed

    }//GEN-LAST:event_boxAlm2ActionPerformed

    private void boxAlm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxAlm1ActionPerformed

    }//GEN-LAST:event_boxAlm1ActionPerformed

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        // TODO add your handling code here:
        try {
            daoV.setCodProducto(txtProducto.getText());
            daoP.datosSelect(daoV);
            lblValidar.setText("Es valido : " + daoV.getNombre());
            SeleccionBtn(!valido);

            if (daoV.getNombre() == null) {
                btnEditar.setEnabled(false);
                lblValidar.setText("No es valido");
            }

        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnValidarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Datos data = new Datos();
                Editar edit = new Editar();
                edit.setLocationRelativeTo(null);
                edit.setVisible(true);
                //    new Editar().setVisible(true);
            }
        });
    }

    private void datosSelect() {
        lista = dao.datosSelect();
        model.setRowCount(0);
        for (Datos dat : lista) {
            Object[] objeto = new Object[6];
            objeto[0] = dat.getIdStock();
            objeto[1] = dat.getCodProducto();
            objeto[2] = dat.getCantidad();
            objeto[3] = dat.getFechaIngreso();
            objeto[4] = dat.getFechaCaducidad();
            objeto[5] = dat.getUbicacion();
            model.addRow(objeto);
        }

    }

    private void vistaMenu() {
        Menu menu = new Menu();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.dispose();
    }

    private void SeleccionBtn(boolean btn) {
        btnEditar.setEnabled(btn);
        btnValidar.setEnabled(btn);
        btnSeleccionar.setEnabled(!btn);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox boxAlm1;
    private javax.swing.JCheckBox boxAlm2;
    private javax.swing.JCheckBox boxAlm3;
    private javax.swing.JCheckBox boxAlm4;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton btnValidar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlblID;
    private javax.swing.JLabel lblAdminAutorizacion;
    private javax.swing.JLabel lblValidar;
    private javax.swing.JTable tblEditar;
    private javax.swing.JTextField txtCantidad;
    private com.toedter.calendar.JDateChooser txtDteFechaIngreso;
    private javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables
}
