/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.entrega;

import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.Reader;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import dao.DaoDatos;
import dao.DaoHistorial;
import dao.DaoProducto;
import dao.impl.DaoImplDatos;
import dao.impl.DaoImplHistorial;
import dao.impl.DaoImplProducto;
import entidades.Datos;
import entidades.Historial;
import entidades.Producto;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import util.Memoria;
import vista.LoginAdmin;
import vista.Menu;

/**
 *
 * @author antho
 */
public class Añadir extends javax.swing.JFrame {

    private DaoDatos dao;
    private DaoProducto daoP;
    private Producto daoV;

    private List<Datos> lista;
    public JTable table;
    public DefaultTableModel model;
    private Datos data;
    private String fechaCad;
    private boolean Cad;

    private DaoHistorial daoH;
    private Historial dataH;
    DateTimeFormatter formato;
    DateTimeFormatter formato2;

    /**
     * Creates new form añadir
    */
    
    public Añadir() {

        initComponents();
        dao = new DaoImplDatos();
        data = new Datos();

        daoP = new DaoImplProducto();
        daoV = new Producto();

        formato = DateTimeFormatter.ofPattern("yyyy-MM-dd");

        model = (DefaultTableModel) tblAñadir.getModel();
        formato2 = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

        daoH = new DaoImplHistorial();
        dataH = new Historial();

        datosSelect();
        lblValidar.setText("");
        lblSeleccionAlmacen.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAñadir = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        boxAlm4 = new javax.swing.JCheckBox();
        boxAlm3 = new javax.swing.JCheckBox();
        boxAlm2 = new javax.swing.JCheckBox();
        boxAlm1 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        lblValidar = new javax.swing.JLabel();
        txtProveedorCodigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JSpinner();
        btnIngresar1 = new javax.swing.JButton();
        jblpathQR = new javax.swing.JLabel();
        lblSeleccionAlmacen = new javax.swing.JLabel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Añadir Entrega");

        btnIngresar.setBackground(new java.awt.Color(0, 0, 0));
        btnIngresar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("SCANNER QR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo del producto    :");

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad                              :");

        txtProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductoActionPerformed(evt);
            }
        });

        tblAñadir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Cantidad", "Fecha ingreso", "Fecha Caducidad", "Ubicacion", "Proveedor"
            }
        ));
        jScrollPane1.setViewportView(tblAñadir);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(boxAlm4);
        boxAlm4.setForeground(new java.awt.Color(255, 255, 255));
        boxAlm4.setText("4");
        boxAlm4.setContentAreaFilled(false);
        boxAlm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxAlm4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(boxAlm3);
        boxAlm3.setForeground(new java.awt.Color(255, 255, 255));
        boxAlm3.setText("3");
        boxAlm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxAlm3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(boxAlm2);
        boxAlm2.setForeground(new java.awt.Color(255, 255, 255));
        boxAlm2.setText("2");
        boxAlm2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxAlm2MouseClicked(evt);
            }
        });
        boxAlm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxAlm2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(boxAlm1);
        boxAlm1.setForeground(new java.awt.Color(255, 255, 255));
        boxAlm1.setText("1");
        boxAlm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxAlm1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Almacén                              :");

        lblValidar.setForeground(new java.awt.Color(255, 51, 51));
        lblValidar.setText("jLabel2");
        lblValidar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblValidarKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Codigo Proveedor               :");

        btnIngresar1.setBackground(new java.awt.Color(0, 0, 0));
        btnIngresar1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnIngresar1.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar1.setText("Añadir Producto");
        btnIngresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar1ActionPerformed(evt);
            }
        });

        jblpathQR.setForeground(new java.awt.Color(0, 204, 0));

        lblSeleccionAlmacen.setForeground(new java.awt.Color(255, 51, 51));
        lblSeleccionAlmacen.setText("jLabel3");
        lblSeleccionAlmacen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblSeleccionAlmacenKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(59, 59, 59)
                                    .addComponent(boxAlm1)
                                    .addGap(28, 28, 28)
                                    .addComponent(boxAlm2)
                                    .addGap(30, 30, 30)
                                    .addComponent(boxAlm3)
                                    .addGap(28, 28, 28)
                                    .addComponent(boxAlm4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(56, 56, 56)
                                .addComponent(txtProveedorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(lblSeleccionAlmacen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(65, 65, 65))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2)
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblValidar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(260, 260, 260))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(57, 57, 57))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnIngresar)
                                .addGap(302, 302, 302)
                                .addComponent(btnIngresar1)
                                .addGap(68, 68, 68))))
                    .addComponent(jblpathQR, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValidar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(boxAlm4)
                        .addComponent(boxAlm3)
                        .addComponent(lblSeleccionAlmacen))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(boxAlm2)
                        .addComponent(boxAlm1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txtProveedorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(btnIngresar1))
                .addGap(5, 5, 5)
                .addComponent(jblpathQR)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoActionPerformed
        try {
            daoV.setCodProducto(txtProducto.getText().toUpperCase());
            daoP.datosSelect(daoV);

            if (daoV.getNombre() != null) {
                lblValidar.setText("Es valido : " + daoV.getNombre());
                btnIngresar1.setEnabled(true);

            } else {
                btnIngresar1.setEnabled(false);
                lblValidar.setText("No es valido");
            }

        } catch (Exception e) {
        }

    }//GEN-LAST:event_txtProductoActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        procesoQR();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        vistaMenu();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        vistaEliminar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        vistaEditarBloqueado();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void boxAlm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxAlm4ActionPerformed

    }//GEN-LAST:event_boxAlm4ActionPerformed

    private void boxAlm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxAlm3ActionPerformed

    }//GEN-LAST:event_boxAlm3ActionPerformed

    private void boxAlm2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxAlm2MouseClicked

    }//GEN-LAST:event_boxAlm2MouseClicked

    private void boxAlm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxAlm2ActionPerformed

    }//GEN-LAST:event_boxAlm2ActionPerformed

    private void boxAlm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxAlm1ActionPerformed

    }//GEN-LAST:event_boxAlm1ActionPerformed

    private void lblValidarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblValidarKeyTyped
        // TODO add your handling code here:


    }//GEN-LAST:event_lblValidarKeyTyped

    private void btnIngresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar1ActionPerformed
        // TODO add your handling code here:
        if (!txtProducto.getText().isBlank()
                && !txtCantidad.getValue().equals("0")
                && (boxAlm1.isSelected() || boxAlm2.isSelected() || boxAlm3.isSelected() || boxAlm4.isSelected())) {

            datos();
            txtProducto.setText("");
            txtCantidad.setValue(0);
            buttonGroup1.clearSelection();
            txtProveedorCodigo.setText("");
            txtProducto.setEnabled(true);
            txtProveedorCodigo.setEnabled(true);
            txtCantidad.setEnabled(true);
            datosSelect();
        } else {
            JOptionPane.showMessageDialog(null, "Falta Ingresar datos",
                    "Información",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnIngresar1ActionPerformed

    private void lblSeleccionAlmacenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblSeleccionAlmacenKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSeleccionAlmacenKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Añadir añadir1 = new Añadir();
                añadir1.setLocationRelativeTo(null);
                añadir1.setVisible(true);
                //      new añadir().setVisible(true);
            }
        });
    }

    private void vistaEditarBloqueado() {
        LoginAdmin log = new LoginAdmin();
        log.setVisible(true);
        log.setLocationRelativeTo(null);
        this.dispose();
    }

    private void datos() {

        LocalDateTime fechaIngreso = LocalDateTime.now();

        LocalDate localFechaEntrega = fechaIngreso.toLocalDate();

        String strFechaEntrega = fechaIngreso.format(formato);
        String strFechaCaducidad = localFechaEntrega.plusDays(10).format(formato);

        String almacen = "";
        if (boxAlm1.isSelected()) {
            almacen = "ALMACEN 1";
        } else if (boxAlm2.isSelected()) {
            almacen = "ALMACEN 2";
        } else if (boxAlm3.isSelected()) {
            almacen = "ALMACEN 3";
        } else if (boxAlm4.isSelected()) {
            almacen = "ALMACEN 4";
        }

        if (Cad) {
            fechaCad = strFechaCaducidad;
        }

        envioDatos(strFechaEntrega, fechaCad, almacen);

        Cad = true;
    }

    private void vistaEliminar() {
        Eliminar tblEliminar = new Eliminar();
        tblEliminar.setVisible(true);
        tblEliminar.setLocationRelativeTo(null);
        this.dispose();
    }

    private void vistaMenu() {
        Menu menu = new Menu();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.dispose();
    }

    private void procesoQR() {
        Reader lector = new MultiFormatReader();
        JFileChooser ventanaDoc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de imagen", "jpg", "jpeg", "png");
        ventanaDoc.setFileFilter(filtro);
        int rs = ventanaDoc.showOpenDialog(null);
        if (rs == JFileChooser.APPROVE_OPTION) {
            BufferedImage imagen;
            File file = ventanaDoc.getSelectedFile();
            if (filtro.accept(file)) {
                jblpathQR.setText(" Archivo seleccionado ");
                File ubicacionImagen = new File(file.getAbsolutePath());
                try {
                    System.out.println(ubicacionImagen);
                    imagen = ImageIO.read(ubicacionImagen);
                    LuminanceSource fuente = new BufferedImageLuminanceSource(imagen);
                    BinaryBitmap mapaBits = new BinaryBitmap(new HybridBinarizer(fuente));
                    try {
                        Result resultado = lector.decode(mapaBits);
                        String texto = resultado.getText();
                        String[] datosSeparados = texto.split(",");

                        if (datosSeparados.length == 4) {

                            String codProd = datosSeparados[0].trim();
                            String cantidad = datosSeparados[1].trim();
                            String fechaCaducidad = datosSeparados[2].trim();
                            String codProv = datosSeparados[3].trim();

                            txtProducto.setText(codProd);
                            txtCantidad.setValue(Integer.valueOf(cantidad));
                            txtProveedorCodigo.setText(codProv);

                            fechaCad = fechaCaducidad;
                            Cad = false;
                            txtProducto.setEnabled(Cad);
                            txtCantidad.setEnabled(Cad);
                            txtProveedorCodigo.setEnabled(Cad);
                            lblSeleccionAlmacen.setText("<- Seleccione");

                        } else {
                            jblpathQR.setText("El código QR no contiene suficientes datos.");
                            jblpathQR.setForeground(Color.RED);
                        }
                    } catch (Exception e) {
                        jblpathQR.setText("No se pudo leer el código QR.");
                        jblpathQR.setForeground(Color.RED);
                    }
                } catch (IOException e) {
                    jblpathQR.setText("Problemas con la imagen");
                    jblpathQR.setForeground(Color.RED);
                }
            } else {
                jblpathQR.setText(" Tipo de archivo incorrecto");
                jblpathQR.setForeground(Color.RED);
            }

        } else {
            jblpathQR.setText(" No se seleccionó ningún archivo.");
            jblpathQR.setForeground(Color.RED);
        }

    }

    private void envioDatos(String entrega, String caducidad, String almacen) {
        data.setCodProducto(txtProducto.getText().toUpperCase());
        data.setCantidad(Integer.parseInt(txtCantidad.getValue().toString()));
        data.setFechaIngreso(entrega);
        data.setFechaCaducidad(caducidad);
        data.setUbicacion(almacen);
        data.setIdProveedor(txtProveedorCodigo.getText());
        dao.datosInsertar(data);

        String ahoraH = "Producto: " + txtProducto.getText() + "\n "
                + "Cantidad: " + txtCantidad.getValue() + "\n "
                + "Almacen: " + almacen + "\n "
                + "Proveedor: " + txtProveedorCodigo.getText() + "\n "
                + "Entrega: " + entrega;

        dataH.setIdStock(0);
        dataH.setIdUsuario((String) Memoria.get("codigoEmpleado"));
        dataH.setHistorial("AÑADIR:");
        dataH.setFechaCambio(LocalDateTime.now().format(formato2));
        dataH.setDescripcion(ahoraH);
        daoH.userInsertar(dataH);

    }

    private void datosSelect() {
        lista = dao.datosSelect();
        model.setRowCount(0);
        for (Datos dat : lista) {
            Object[] objeto = new Object[7];
            objeto[0] = dat.getIdStock();
            objeto[1] = dat.getCodProducto();
            objeto[2] = dat.getCantidad();
            objeto[3] = dat.getFechaIngreso();
            objeto[4] = dat.getFechaCaducidad();
            objeto[5] = dat.getUbicacion();
            objeto[6] = dat.getIdProveedor();
            model.addRow(objeto);

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox boxAlm1;
    private javax.swing.JCheckBox boxAlm2;
    private javax.swing.JCheckBox boxAlm3;
    private javax.swing.JCheckBox boxAlm4;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnIngresar1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblpathQR;
    private javax.swing.JLabel lblSeleccionAlmacen;
    private javax.swing.JLabel lblValidar;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JTable tblAñadir;
    private javax.swing.JSpinner txtCantidad;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtProveedorCodigo;
    // End of variables declaration//GEN-END:variables
}
